# Generated by Django 4.1.9 on 2023-05-27 23:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pieza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='coleccion',
            fields=[
                ('id_coleccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('id_coleccionista', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='pieza',
            name='id_coleccion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coleccionista',
            name='fecha_registro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
