# Generated by Django 4.1.9 on 2023-05-27 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pieza', '0002_coleccion_pieza_id_coleccion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coleccion',
        ),
        migrations.RemoveField(
            model_name='pieza',
            name='id_coleccion',
        ),
    ]
