# Generated by Django 4.1.9 on 2023-05-28 00:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pieza', '0003_delete_coleccion_remove_pieza_id_coleccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha_venta',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
