# Generated by Django 4.1.9 on 2023-05-28 00:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieza', '0004_alter_compra_fecha_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieza',
            name='año',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
